const colors = {
  light: {
    background: "#ffffff",
    foreground: "#0f172a",
    card: "#f8fafc",
    cardForeground: "#0f172a",
    primary: "#1e40af",
    primaryForeground: "#ffffff",
    secondary: "#eff6ff",
    secondaryForeground: "#1e3a5f",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#f59e0b",
    accentForeground: "#ffffff",
    border: "#e2e8f0",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#16a34a",
    successForeground: "#ffffff",
    tint: "#1e40af",
    tabIconDefault: "#94a3b8",
    tabIconSelected: "#1e40af",
  },
  dark: {
    background: "#0f172a",
    foreground: "#f8fafc",
    card: "#1e293b",
    cardForeground: "#f8fafc",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#1e3a5f",
    secondaryForeground: "#bfdbfe",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    accent: "#f59e0b",
    accentForeground: "#ffffff",
    border: "#334155",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    tint: "#3b82f6",
    tabIconDefault: "#475569",
    tabIconSelected: "#3b82f6",
  },
};

export default colors;
