import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import storageRouter from "./storage.js";
import authRouter from "./auth.js";
import dashboardRouter from "./dashboard.js";
import productsRouter from "./products.js";
import categoriesRouter from "./categories.js";
import subcategoriesRouter from "./subcategories.js";
import brandsRouter from "./brands.js";
import inventoryRouter from "./inventory.js";
import ordersRouter from "./orders.js";
import customersRouter from "./customers.js";
import suppliersRouter from "./suppliers.js";
import purchasesRouter from "./purchases.js";
import employeesRouter from "./employees.js";
import deliveryRouter from "./routes-delivery.js";
import cashExpensesRouter from "./cash-expenses.js";
import branchesRouter from "./branches.js";
import salesRouter from "./sales.js";
import reportsRouter from "./reports.js";
import notifSettingsRouter from "./notifications-settings.js";
import usersRouter from "./users.js";
import ledgerRouter from "./ledger.js";
import customerTransactionsRouter from "./customer-transactions.js";
import supplierTransactionsRouter from "./supplier-transactions.js";
import storeRouter from "./store.js";
import bookCatalogRouter from "./book-catalog.js";
import adminRouter from "./admin.js";
import businessRouter from "./business.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(subcategoriesRouter);
router.use(brandsRouter);
router.use(inventoryRouter);
router.use(ordersRouter);
router.use(customersRouter);
router.use(suppliersRouter);
router.use(purchasesRouter);
router.use(employeesRouter);
router.use(deliveryRouter);
router.use(cashExpensesRouter);
router.use(branchesRouter);
router.use(salesRouter);
router.use(reportsRouter);
router.use(notifSettingsRouter);
router.use(usersRouter);
router.use(ledgerRouter);
router.use(customerTransactionsRouter);
router.use(supplierTransactionsRouter);
router.use(storeRouter);
router.use(bookCatalogRouter);
router.use(adminRouter);
router.use(businessRouter);

export default router;
